# Generated by Django 4.2.6 on 2023-11-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_favorite',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.TextField(),
        ),
    ]
